name: build-app

on:
  workflow_dispatch:

jobs:

  build:

    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install the signing keystore
        run: |
          base64 --decode <<< "$KEYSTORE_CONTENT" > release.jks
          cat << EOF >> android/gradle.properties
          KEYSTORE_PATH=$(pwd)/release.jks
          KEYSTORE_PASSWORD=$KEYSTORE_PASSWORD
          KEY_ALIAS=$KEY_ALIAS
          EOF
        env:
          KEYSTORE_CONTENT: ${{ secrets.ANDROID_KEYSTORE_CONTENT_BASE64 }}
          KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}

      - name: Build APK
        run: |
          cd android
          ./gradlew assembleRelease --no-daemon

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v7
        with:
          name: slipdroid-apk
          path: android/app/build/outputs/**/*.apk
